AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""

Parameters:
    ImageId:
        Description: AMI Golden Image
        Type: String
        Default: "ami-0b5eea76982371e91"
    InstanceType:
        Description: Hardware
        Type: String
        Default: "t2.micro"
    KeyName:
        Description: SSH Key Pair
        Type: String
        Default: "ec2-user"
    UserData:
        Description: Boot time actions
        Type: String
        Default: |
            Content-Type: multipart/mixed; boundary="//"
            MIME-Version: 1.0

            --//
            Content-Type: text/cloud-config; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-Disposition: attachment; filename="cloud-config.txt"

            #cloud-config
            package_update: true
            package_upgrade: true
            package_reboot_if_required: true
            power_state:
                delay: now
                mode: poweroff
                message: Powering off
                timeout: 2
                condition: true
            cloud_final_modules:
            - [scripts-user, always]

            --//
            Content-Type: text/x-shellscript; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-Disposition: attachment; filename="userdata.txt"

Resources:

    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: !Ref ImageId
            InstanceType: !Ref InstanceType
            KeyName: !Ref KeyName
            AvailabilityZone: !Sub "${AWS::Region}a"
            UserData:
                Fn::Base64:
                    !Ref UserData
            Tags: 
              - 
                Key: "Name"
                Value: "test1"
